#!/bin/bash
set -e

cd /app
composer install
yarn install
yarn encore dev
chmod 777 -R vendor/
chmod 777 -R node_modules/
chmod 777 -R public/build/
bin/console doctrine:migrations:migrate -n
bin/console doctrine:fixtures:load -n
bin/console assets:install --symlink public
# bin/console server:run 0.0.0.0:8000