stages:
  - deploy:staging
  - tests:functional

deploy:staging:
  stage: deploy:staging
  script:
    # stop messenger
    - sudo ps axf | grep "configurable-http-proxy" | grep -v grep | awk '{print "sudo kill -9 " $1}' | sh || true
    # deploy
    - sudo ln -fs $PWD /opt/remotelabz
    - sudo ln -fs $PWD/config/apache/100-remotelabz.conf /etc/apache2/sites-enabled/100-remotelabz.conf
    - sudo ln -fs $PWD/config/apache/200-remotelabz-ssl.conf /etc/apache2/sites-enabled/200-remotelabz-ssl.conf
    - mkdir -p config/jwt
    - openssl genpkey -pass pass:$JWT_PASSPHRASE -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096 -out config/jwt/private.pem
    - openssl pkey -passin pass:$JWT_PASSPHRASE -in config/jwt/private.pem -out config/jwt/public.pem -pubout
    - cp .env .env.local
    - echo JWT_PASSPHRASE=$JWT_PASSPHRASE | tee -a .env.local
    - echo WEBSOCKET_PROXY_PORT=8000 | tee -a .env.local
    - echo WEBSOCKET_PROXY_API_PORT=8001 | tee -a .env.local
    - . ./.env.local
    - php composer.phar install --no-progress --no-suggest
    - yarn install
    - yarn encore prod
    - php bin/console doctrine:database:drop --force || true
    - php bin/console doctrine:database:create
    - php bin/console doctrine:migrations:migrate -n || true
    - php bin/console doctrine:fixtures:load -n
    - sudo systemctl stop remotelabz || true
    - sudo ln -fs $PWD/bin/remotelabz.service /etc/systemd/system/remotelabz.service
    - sudo systemctl daemon-reload
    - sudo systemctl start remotelabz
    - sudo nohup configurable-http-proxy > configurable-http-proxy.log &
    - sudo chgrp -R www-data $PWD /opt/remotelabz
    - sudo chmod -R g+rwx $PWD /opt/remotelabz
    - sudo service apache2 reload
  environment:
    name: staging
    url: https://staging.remotelabz.com/
    on_stop: stop:staging
  tags:
    - staging
  only:
    - master

tests:functional:
  stage: tests:functional
  variables:
    GIT_STRATEGY: none
  script:
    - php bin/phpunit
  dependencies:
    - deploy:staging
  tags:
    - test
  only:
    - master

stop:staging:
  stage: deploy:staging
  variables:
    GIT_STRATEGY: none
  script:
    - sudo service remotelabz stop
    - ps axf | grep "configurable-http-proxy" | grep -v grep | awk '{print "kill -9 " $1}' | sh || true
  when: manual
  environment:
    name: staging
    action: stop
  tags:
    - staging
  only:
    - master
