#!/usr/bin/env php
<?php

// Variables
$install_log_path = "/var/log/remotelabz/install.log";

// Debug functions
function debug($string, $handle = null) {
    echo $string;
    if ($handle !== null) {
        fprintf($handle, "[%s] %s\n", date(DATE_RFC2822), $string);
    }
}

function warning($string, $handle = null) {
    echo "\e[33mW: $string\e[39m";
    if ($handle !== null) {
        fprintf($handle, "\e[33m[%s] %s\n\e[39m", date(DATE_RFC2822), $string);
    }
}

function error($string, $handle = null) {
    echo "\e[31mE: $string\e[39m";
    if ($handle !== null) {
        fprintf($handle, "\e[31m[%s] %s\n\e[39m", date(DATE_RFC2822), $string);
    }
}

function check_root() {
    $username = posix_getpwuid(posix_geteuid())['name'];
    if ($username != "root") {
        throw new Exception("Installation aborted, root is required! Please launch this script as root or with sudo.\n");
    }
}

function command_exist($cmd) {
    $return = shell_exec(sprintf("which %s", escapeshellarg($cmd)));
    return !empty($return);
}

function check_requirements() {
    if (!command_exist("composer")) {
        throw new Exception("Composer has not been found on your system. Please install Composer to continue.");
    }
}

function do_install($handle) {

}

try {
    check_root();
} catch (Exception $e) {
    error($e->getMessage());
    echo "Exiting...\n";
    exit(1);
}

// Create log folder
if ( !is_dir("/var/log/remotelabz") ) {
    mkdir("/var/log/remotelabz");
}

$handle = fopen($install_log_path, "a");

try {
    check_requirements();
    do_install($handle);
} catch (Exception $e) {
    echo "Error ❌\n";
    error($e->getMessage(), $handle);
    echo "\nExiting...\n";
    fclose($handle);
    exit(1);
}

fclose($handle);
