<?php

namespace AppBundle\Repository;

/**
 * Affected_IPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Affected_IPRepository extends \Doctrine\ORM\EntityRepository
{
}
