<?php

namespace AppBundle\Repository;

/**
 * ConfigReseauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigReseauRepository extends \Doctrine\ORM\EntityRepository
{
}
