<?php

namespace AppBundle\Repository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends \Doctrine\ORM\EntityRepository
{

    public function getNotUsedDeviceQueryBuilder()
    {
        $qb = $this->_em->createQueryBuilder();
        return $qb->select('dev')
            ->from('AppBundle:Device', 'dev')
            ->where($qb->expr()->isNull('dev.pod'))
//            ->andWhere($qb->expr()->isNull('net.config_reseau'));
           ;
        ;
    }
}

