<?php

namespace AppBundle\Repository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends \Doctrine\ORM\EntityRepository
{

//    public function getNotUsedSystemQueryBuilder()
//    {
//        $qb =   $this
//            ->createQueryBuilder('d')
//            ->join('d.systeme','sys')
//            ->addSelect('sys');
//            $qb->where($qb->expr()->isNull('d.systeme' ))
////                ->andWhere($qb->expr()->isNull('net.device' ));
//           ;
//        return $qb;
//    }
}

