<?php

namespace AppBundle\Repository;

/**
 * HyperviseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HyperviseurRepository extends \Doctrine\ORM\EntityRepository
{
}
