<?php

namespace AppBundle\Repository;

/**
 * LABRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LABRepository extends \Doctrine\ORM\EntityRepository
{
        function getLabWithoutTpQueryBuilder(){
            $qb = $this->_em->createQueryBuilder();
            return $qb->select('lab')
                ->from('AppBundle:LAB', 'lab')
                ->where($qb->expr()->isNull('lab.tp'));
        }





}
