<?php

namespace AppBundle\Repository;

/**
 * NetworkUsedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NetworkUsedRepository extends \Doctrine\ORM\EntityRepository
{
}
