<?php

namespace AppBundle\Repository;

/**
 * Network_InterfaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Network_InterfaceRepository extends \Doctrine\ORM\EntityRepository
{
}
