<?php

namespace AppBundle\Repository;

/**
 * Param_SystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Param_SystemRepository extends \Doctrine\ORM\EntityRepository
{
}
