<?php

namespace AppBundle\Repository;

/**
 * plage_ipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class plage_ipRepository extends \Doctrine\ORM\EntityRepository
{
}
