<?php

namespace AppBundle\Repository;

/**
 * PODRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PODRepository extends \Doctrine\ORM\EntityRepository
{

    public function getNotUsedPodQueryBuilder()
    {
        $qb = $this->_em->createQueryBuilder();
        return $qb->select('pod')
            ->from('AppBundle:POD', 'pod')
           // ->where($qb->expr()->isNull('pod.lab'))
//            ->andWhere($qb->expr()->isNull('net.config_reseau'));
            ;
        ;
    }
}
