<?php

namespace AppBundle\Repository;

/**
 * PODRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PODRepository extends \Doctrine\ORM\EntityRepository
{
}
