<?php

namespace AppBundle\Repository;

/**
 * ProprieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProprieteRepository extends \Doctrine\ORM\EntityRepository
{
}
