<?php

namespace AppBundle\Repository;

/**
 * RunRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RunRepository extends \Doctrine\ORM\EntityRepository
{
}
