<?php

namespace AppBundle\Repository;

/**
 * SystemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemeRepository extends \Doctrine\ORM\EntityRepository
{

//    public function getNotUsedSystemeQueryBuilder()
//    {
//        return  $this
//            ->createQueryBuilder('s')
//            ->join('s.id')
//            ->where('a.published = :published')
//            ->setParameter('published', true)
//            ;
//    }
}
