<?php

namespace AppBundle\Repository;

/**
 * SystemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemeRepository extends \Doctrine\ORM\EntityRepository
{

   public function getNotUsedSystemeQueryBuilder()
    {
		 $em = $this->getEntityManager();
        $qb_used_systeme = $em->createQueryBuilder()
        ->select('sys')
		->from('AppBundle:Systeme', 'sys')
		;
		/*->innerJoin('AppBundle:Device','dev', 'WITH', 'dev.systeme = sys.id')
		->getQuery()
		->getArrayResult();*/
		
//		$qb = $em->createQueryBuilder();
		return $qb_used_systeme;
/*		->select('sys')
		->from('AppBundle:Systeme', 'sys')
		->where($qb->expr()->notin('sys.id',':qb_used_systeme'))
		->setParameter('qb_used_systeme',$qb_used_systeme)
		;*/
		
       
   }
}
