<?php

namespace AppBundle\Repository;

/**
 * SystemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemeRepository extends \Doctrine\ORM\EntityRepository
{
}
