<?php

namespace UserBundle\Repository;

/**
 * UserGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupRepository extends \Doctrine\ORM\EntityRepository
{
	

	
	public function GroupsOfUser($user) {
	$qb=$this->createQueryBuilder('ug');
	
	$qbl=$qb->where('ug.user = :user')
		->setParameter('user',$user);
			
	return $qbl->getQuery()->getResult();

    }
	
}
