<?php

namespace RemoteLabz;

use M1\Env\Parser;

class Dotenv
{
    protected $file;

    protected $data;

    public function __construct($file)
    {
        $this->file = $file;
    }

    public static function create($file) : self
    {
        return new static($file);
    }

    public function parse() : self
    {
        $content = Parser::parse(file_get_contents($this->file));
        $this->data = $content;
        return $this;
    }

    public function get($name)
    {
        if (array_key_exists($name, $this->data)) {
            return $this->data[$name];
        }
    }

    public function set($name, $value) : self
    {
        $this->data[$name] = $value;
        return $this;
    }

    public function save() : self
    {
        $string = "# This file is automatically generated.\n\n";

        foreach ($this->data as $key => $value) {
            $string .= $key;
            $string .= "=";
            $string .= (is_string($value) ? "\"" : "");
            $string .= addslashes($value);
            $string .= (is_string($value) ? "\"" : "");
            $string .= "\n";
        }

        file_put_contents($this->file, $string);

        return $this;
    }
}