name: Migration
type: container
icon: null
operatingSystem: 6
flavor: 1
controlProtocol:
    - 5
hypervisor: 4
brand: Debian
model: 'Version Bulleye'
description: Migration
cpu: 1
core: null
socket: null
thread: null
context: remotelabz
config_script: embedded
ethernet: 1
