name: test
type: vm
icon: Server_Linux.png
operatingSystem: 5
flavor: 1
controlProtocol: ''
hypervisor: 3
brand: ''
model: ''
description: test
cpu: 1
core: null
socket: null
thread: null
context: remotelabz
config_script: embedded
ethernet: 1
