---
context: remotelabz
config_script: embedded
name: Debian-cnt
icon: Server_Linux.png
cpu: 1
ethernet: 1
console: vnc
description: Debian-cnt
brand: Debian
model: Stable
type: container
flavor: 1
operatingSystem: 8
hypervisor: 4
controlProtocol: [5]
interfaces: 0

...
