---
context: remotelabz
config_script: embedded
name: Linux Alpine
icon: Server_Linux.png
cpu: 1
ethernet: 1
console: vnc
description: Linux Alpine
brand: Test
model: Test model
type: vm
flavor: 2
operatingSystem: 5
hypervisor: 3
controlProtocol: ''
interfaces: 1
...
